import { LineageKey } from './lineages';

export interface ArchetypeCard {
  name: string;
  role: string;
  existentialField: string;
  gift: string;
  shadow: string;
  elderQuestion: string;
  canonicalAnchor: string;
}

export interface LineageArchetypes {
  diagnosticQuestions: string[];
  archetypes: ArchetypeCard[];
}

export const LINEAGE_ARCHETYPES: Record<LineageKey, LineageArchetypes> = {

  default: {
    diagnosticQuestions: [
      "What wound do you carry that you have never shown to another person?",
      "What have you destroyed — and what was born in the wreckage?",
      "What calls you forward that you keep refusing to answer?",
    ],
    archetypes: [
      {
        name: "The Wounded Healer",
        role: "The one whose wound becomes the instrument",
        existentialField: "Suffering as initiation — the wound that opens the gift",
        gift: "The capacity to hold others in their darkest passages because you have walked there yourself",
        shadow: "Using others' wounds to avoid your own — healing as flight from the self",
        elderQuestion: "What would remain of your purpose if you were no longer in pain?",
        canonicalAnchor: "Chiron, the centaur, accidentally wounded by one of Heracles's poisoned arrows — a wound from a hydra's venom that, because Chiron was immortal, could never close and could never kill him. He spent the rest of his long life teaching the greatest healers and heroes of Greek myth (Asclepius among them) while carrying his own agony untreated, until he finally traded his immortality to free Prometheus and was allowed to die.",
      },
      {
        name: "The Threshold Guardian",
        role: "The keeper of the between-place",
        existentialField: "Liminality — permanent residency at the crossing point",
        gift: "The ability to stand in uncertainty without collapsing it prematurely into resolution",
        shadow: "Guarding the threshold so well that nothing — including yourself — ever crosses it",
        elderQuestion: "What are you guarding against that you claim to be guarding for?",
        canonicalAnchor: "The fire kept burning at the mouth of the cave in the oldest human dwelling-story — not inside, where it is safe, and not out in the dark, where it is unprotected, but exactly at the seam between the two. Every watcher who has ever tended such a fire has done the same work: staying awake at the border so others can sleep without having to face what moves in the dark themselves.",
      },
      {
        name: "The Descent Maker",
        role: "The one who goes under willingly",
        existentialField: "The necessary downward movement — toward what must be faced",
        gift: "The willingness to lose what must be lost in order to arrive at what cannot be found any other way",
        shadow: "Mistaking descent for collapse — wearing destruction as identity",
        elderQuestion: "Are you descending, or have you simply fallen and named it a choice?",
        canonicalAnchor: "Inanna, Sumerian queen of heaven, descends of her own will to the underworld ruled by her sister Ereshkigal, and at each of the seven gates the gatekeeper takes one more piece of her royal regalia — crown, jewelry, robe — until she arrives before her sister's throne with nothing left to remove. She is killed there and hung on a hook, and only returns to the living world through the intervention of others, changed by what the descent cost her.",
      },
    ],
  },

  maya: {
    diagnosticQuestions: [
      "What house of Xibalba are you moving through right now — which Lord governs this ordeal?",
      "What in your life has been stripped away that you once believed was essential to your survival?",
      "The corn must die in the ground before it can become food. What in you is still refusing the ground?",
    ],
    archetypes: [
      {
        name: "The Corn Seed",
        role: "The life-force that must descend before it can rise",
        existentialField: "The milpa cycle — death underground as the condition of future abundance",
        gift: "The knowledge that descent is not failure but preparation — the seed knows what the standing stalk has forgotten",
        shadow: "Refusing to be planted — remaining a seed forever, intact and sterile",
        elderQuestion: "What ground are you refusing to enter because you fear you will not emerge?",
        canonicalAnchor: "Hun Hunahpu, defeated and beheaded by the Lords of Xibalba after losing the ball game, has his skull hung in a barren calabash tree as a warning — and the tree immediately fruits for the first time, the skull itself becoming one of the gourds. When the maiden Ix Kik' comes to see the tree, the skull speaks to her and spits into her outstretched hand, conceiving the Hero Twins who will one day avenge him.",
      },
      {
        name: "The Ball Court Player",
        role: "The one who plays the game that cannot be refused",
        existentialField: "The contest with Xibalba — where the stakes are always life itself",
        gift: "The understanding that the Lords of death must be met with cunning and sacred play, not with force",
        shadow: "Becoming so skilled at the game that you forget the game was meant to be survived, not perfected",
        elderQuestion: "What challenge before you are you treating as a performance when it requires your life?",
        canonicalAnchor: "Sent by the Lords of Xibalba into the House of Darkness — one of several trial-houses meant to destroy them, alongside the House of Jaguars, Knives, and Cold — the Hero Twins Hunahpu and Xbalanque are given a torch and two cigars they must return unburned by morning. Rather than burning them for light as expected, they attach a macaw feather that glows like fire and fireflies that glow like the cigars' embers, surviving the house by outwitting its actual test rather than performing the obvious response to it.",
      },
      {
        name: "Ix K'ik' — Blood Moon",
        role: "The one who receives the impossible and carries it forward",
        existentialField: "Conception through the word — the power to bring forth life from what appeared to be only death",
        gift: "The capacity to receive what falls from the dead place and transform it into living continuation",
        shadow: "Carrying the seed of another's destiny while never planting your own",
        elderQuestion: "Whose story are you gestating — and when does your own story begin?",
        canonicalAnchor: "Ix K'ik', daughter of one of the Lords of Xibalba, comes out of curiosity to see the talking skull hanging in the calabash tree, and when she extends her hand as it asks, Hun Hunahpu's skull spits into her palm — an act that conceives the Hero Twins without any further contact. Her own father, discovering she is pregnant by a dead enemy, orders her killed, and she survives only by convincing his messenger owls to spare her.",
      },
      {
        name: "The Ajq'ij",
        role: "The daykeeper — the one who reads the living count",
        existentialField: "Time as sacred architecture — each day a force, not an empty container",
        gift: "The ability to stand inside time's pattern and name what it is asking of those who move through it",
        shadow: "Reading the count for others while refusing to read your own nahual's demand",
        elderQuestion: "What does your own nahual ask of you that you have been too busy counting days to hear?",
        canonicalAnchor: "The Chol Q'ij is the 260-day K'iche' sacred calendar, formed by twenty named day-signs (nahuales) each cycling through thirteen numbered tones — every day carrying its own specific character and demand, read by a trained daykeeper (ajq'ij) rather than experienced as undifferentiated time. The calendar has run continuously and without interruption since before the Spanish invasion, its keepers still counting the same round today.",
      },
      {
        name: "Vucub Caquix",
        role: "The false light who claims to be the sun before the sun exists",
        existentialField: "Premature glory — the brilliance that is only borrowed, worn as if it were earned",
        gift: "The lesson only failure can teach — that true light does not need to announce itself",
        shadow: "Believing your own performance of radiance so completely that correction feels like annihilation",
        elderQuestion: "What are you calling your own brilliance that was only ever borrowed light?",
        canonicalAnchor: "Vucub Caquix, the Seven Macaw, ruled in the age before true daylight and declared himself both sun and moon, his jeweled teeth and metal eyes gleaming enough to make the claim briefly plausible in a world still dim. The Hero Twins Hunahpu and Xbalanque shot him from his perch with a blowgun, then — disguised as healers — pulled his dazzling teeth and eyes under the pretense of curing his resulting toothache, leaving him diminished and stripped of the borrowed brilliance he had mistaken for his own.",
      },
      {
        name: "Huracan, Heart of Sky",
        role: "The one-legged creator who speaks the world into being and unmakes what fails to answer",
        existentialField: "Creation as speech and trial — the made world tested against what it was spoken to become",
        gift: "The clarity to unmake what did not answer rightly, without sentiment, so that what comes next can be truer",
        shadow: "Destroying prematurely — mistaking a slow answer for no answer at all",
        elderQuestion: "What have you already spoken into being that has not yet had the chance to answer you?",
        canonicalAnchor: "Huracan, Heart of Sky, first spoke the world and its creatures into being together with the other Framers and Shapers, but the earliest attempts at making people failed the one test that mattered: the mud people dissolved and could not speak the makers' names, and the wood people had bodies but no hearts or memory, so a flood and their own animals and tools turned against them. Only the third attempt — people formed from white and yellow corn — could speak, remember, and give proper thanks, and that generation is the one still living.",
      },
    ],
  },

  norse: {
    diagnosticQuestions: [
      "What is already woven in your wyrd that you have been pretending is still a choice?",
      "What have you sacrificed that was actually worth sacrificing — and what did you receive in return?",
      "Where is the frost-giant operating in your life — the force that destroys what it cannot control?",
    ],
    archetypes: [
      {
        name: "The Hanged One",
        role: "The one who surrenders to ordeal in order to receive knowledge",
        existentialField: "Wisdom as cost — nothing of worth arrives without sacrifice",
        gift: "The understanding that the runes are not discovered but earned — through the willingness to hang between worlds",
        shadow: "Performing sacrifice without genuine surrender — the gesture without the fall",
        elderQuestion: "What are you pretending to sacrifice while keeping the most important thing safely intact?",
        canonicalAnchor: "Odin, All-Father, hangs himself from the World Tree Yggdrasil for nine full nights, wounded by his own spear and given neither food nor drink by anyone, a sacrifice of himself to himself for knowledge no one could simply hand him. On the ninth night he looks down, cries out, and takes up the runes rising from below — knowledge that could only be received by that exact ordeal, not studied or granted any other way.",
      },
      {
        name: "The Volva",
        role: "The seeress who speaks what fate has already woven",
        existentialField: "Wyrd as already-written — the seeress reads what is, not what might be",
        gift: "The capacity to name what others cannot bear to see — and to name it without flinching",
        shadow: "Using the gift of sight as power over others rather than service to the pattern",
        elderQuestion: "What do you already know that you have been refusing to speak aloud?",
        canonicalAnchor: "The Voluspa opens with Odin riding to the edge of the world to wake a dead volva (seeress) from her grave-mound, compelling her to speak against her own reluctance. She recounts the making of the world, the coming war between gods and giants, the death of Baldur, and the final battle of Ragnarok — speaking the entire fate of the cosmos to its own ruler, who cannot alter what she describes, only hear it.",
      },
      {
        name: "The Wyrd-Bound",
        role: "The one living out what the Norns cut at birth",
        existentialField: "Fate as tapestry — the thread's length was set before the first breath",
        gift: "The freedom that comes from accepting what was always already true — action without the weight of futile resistance",
        shadow: "Using fate as an excuse to abdicate the choices that are genuinely yours to make",
        elderQuestion: "What are you blaming on the Norns that is actually within your own hand to change?",
        canonicalAnchor: "At the well beneath Yggdrasil's roots, the three Norns — Urd (what has become), Verdandi (what is becoming), and Skuld (what shall be) — carve and tend the fates of gods and humans alike, watering the World Tree's roots so it does not wither. Their weaving does not pause for anyone's preference, including Odin's; even the gods live inside the pattern the Norns are cutting, not above it.",
      },
      {
        name: "Freyja's Falcon Cloak",
        role: "The one who moves between worlds by right of what she alone possesses",
        existentialField: "Sovereignty over one's own passage — desire, war, and death held by the same hand without contradiction",
        gift: "The freedom of movement that comes from owning your own crossing, rather than waiting to be granted one",
        shadow: "Hoarding the means of your own freedom while others around you stay grounded and unable to follow",
        elderQuestion: "What is the falcon cloak you already own that you have not yet worn to leave?",
        canonicalAnchor: "Freyja owns a cloak of falcon feathers that lets its wearer fly between worlds, and she lends it freely — to Loki more than once, on errands only that flight could accomplish. As leader of the Valkyries she also claims first choice of the warriors who fall in battle, taking half to her own hall Folkvangr before Odin's Valhalla receives the rest, a sovereignty over passage — desire, war, and death together — that no other deity holds undivided.",
      },
      {
        name: "The Bound Trickster",
        role: "The one whose cunning serves the gods until the day it turns against them",
        existentialField: "Loki at the threshold — the necessary disruptor whose usefulness and danger are the same trait",
        gift: "The recognition that the trickster inside you solves what the earnest part of you cannot",
        shadow: "Waiting so long to be trusted that betrayal becomes the only remaining way to be believed",
        elderQuestion: "Where in you has cleverness curdled into grievance because it was never once thanked?",
        canonicalAnchor: "After engineering the death of Baldur, Loki is finally caught and bound to three stones with the entrails of one of his own sons, and a serpent is fixed above his face to drip venom onto him without ceasing. His wife Sigyn catches the venom in a bowl to spare him, but each time she must turn to empty it, the venom strikes him and his convulsions are felt across the earth as tremors — a punishment that holds until the day of Ragnarok, when he breaks free at last.",
      },
    ],
  },

  taoist: {
    diagnosticQuestions: [
      "What are you forcing right now that the Tao is clearly asking you to release?",
      "Where in your life are you generating the opposite of what you intend through the very effort of your trying?",
      "What would remain if you stopped doing everything you do to make yourself feel safe?",
    ],
    archetypes: [
      {
        name: "The Uncarved Block",
        role: "The one who has not yet been shaped by the world's demands",
        existentialField: "Pu — original nature before the ten thousand things impose their forms",
        gift: "The capacity to receive any shape without losing the root — to be water, not ice",
        shadow: "Mistaking formlessness for undevelopment — using the uncarved block as permission to remain unconscious",
        elderQuestion: "What have you let the world carve away that you now need to recover?",
        canonicalAnchor: "Chapter 28 of the Tao Te Ching describes one who knows the masculine yet holds to the feminine, knows the white yet holds to the black, becoming a channel and a valley for the world — and closes by naming this state p'u, the uncarved block, from which, once cut, all the vessels and tools of civilization are made. The chapter's counsel is that the sage uses these cuttings without ever losing the uncarved wholeness underneath them.",
      },
      {
        name: "The Water Bearer",
        role: "The one who yields and thereby overcomes",
        existentialField: "Wu wei — the power of non-contention, the strength of apparent weakness",
        gift: "The understanding that the softest thing in the world overcomes the hardest — that yielding is not defeat",
        shadow: "Using spiritual yielding to avoid the genuine confrontation that is actually required",
        elderQuestion: "Where is your yielding wisdom — and where is it avoidance wearing wisdom's face?",
        canonicalAnchor: "Chapter 78 of the Tao Te Ching observes that nothing under heaven is as soft and yielding as water, yet for attacking the hard and strong nothing can surpass it, for there is no way to alter it. It closes with the paradox at the center of the whole text: the weak overcomes the strong, the soft overcomes the hard, a truth everyone under heaven knows and almost no one is able to practice.",
      },
      {
        name: "The Cook of Prince Hui",
        role: "The master who moves through the world without friction",
        existentialField: "Skill as Tao-alignment — the naturalness that looks like effortlessness from outside",
        gift: "The capacity to find the spaces that already exist in things and move through them without forcing",
        shadow: "Performing effortlessness as an aesthetic while still driven by the need to be seen as masterful",
        elderQuestion: "Where are you still using your blade on bone — and where have you found the natural spaces?",
        canonicalAnchor: "In the Zhuangzi, Cook Ding butchers an ox for Prince Hui with such effortless precision that the prince asks how his skill became so great, and the cook answers that he no longer sees the whole ox — he perceives the natural openings between joint and tendon and lets his blade find the spaces that were already there, never striking bone. His knife, he says, has cut thousands of oxen over nineteen years and its edge is still as sharp as when it left the whetstone, because it has never once forced its way through anything.",
      },
      {
        name: "The Butterfly Dreamer",
        role: "The one no longer certain which state is the dream and which the dreamer",
        existentialField: "The dissolving boundary between self and transformation — identity as a question, not a fact",
        gift: "The lightness that comes from holding your own identity loosely enough to let it change shape",
        shadow: "Using philosophical uncertainty about the self as a way to avoid ever committing to being anyone",
        elderQuestion: "If you woke up changed tomorrow, which version of you would be the one who was dreaming?",
        canonicalAnchor: "Zhuangzi tells of dreaming he was a butterfly, flitting about pleased with himself and entirely unaware of being Zhuangzi — and then waking, startled, to find himself unmistakably Zhuangzi again. He does not know, he says, whether he is a man who dreamed he was a butterfly, or a butterfly now dreaming he is a man — and he calls this uncertainty itself the transformation of things.",
      },
      {
        name: "The Old Master at the Western Gate",
        role: "The one who leaves civilization behind, but not before writing down the Way",
        existentialField: "Departure as teaching — wisdom offered only once, at the threshold, to whoever is watching the gate",
        gift: "The generosity of the reluctant teacher — giving the essential thing once, completely, without dwelling on it",
        shadow: "Withholding your own wisdom so long, waiting for the right threshold, that it is never given at all",
        elderQuestion: "What have you been saving to say only at your own departure — and why are you waiting for the gate?",
        canonicalAnchor: "According to the traditional account, Laozi grew weary of the decline of the Zhou court and rode an ox westward, intending to leave civilization behind entirely. At the western pass, the gatekeeper Yinxi recognized him and refused to let him pass until he had set his teaching down in writing — and the text he produced there, before continuing west and vanishing from record, became the Tao Te Ching.",
      },
    ],
  },

  greek: {
    diagnosticQuestions: [
      "What is the hamartia — the specific flaw — that keeps generating the same consequence in your life?",
      "Which god have you refused to honor — and in what form has that god returned uninvited?",
      "What oracle have you been given that you have been trying to outrun?",
    ],
    archetypes: [
      {
        name: "The Tragic Hero",
        role: "The one whose greatness and fatal flaw are the same force",
        existentialField: "Hamartia — the specific wound or excess that drives both the rise and the fall",
        gift: "The magnitude that makes the fall meaningful — only the tall tree casts a long shadow",
        shadow: "The inability to see the flaw that everyone else can see — hubris as blindness to one's own pattern",
        elderQuestion: "What quality do you most prize in yourself that is also what is bringing you down?",
        canonicalAnchor: "Oedipus answers the Sphinx's riddle correctly — what walks on four legs at dawn, two at noon, and three at evening is a human being — and frees Thebes from her terror, becoming its king. Yet the entire chain of his triumphs (leaving Corinth to escape a prophecy, killing a stranger on the road, marrying the widowed queen) is the prophecy fulfilling itself exactly, and he spends the play's length discovering, in his own kingdom, that the man he has been hunting is himself.",
      },
      {
        name: "The Orpheus Wound",
        role: "The one who descends for love and loses through looking back",
        existentialField: "The descent into Hades — love as the motive that breaks the final law",
        gift: "The knowledge that some things must be trusted in the dark — that the final moment of the ordeal requires surrender of control",
        shadow: "The compulsion to verify, to look back, to make certain — destroying the thing by refusing to trust it",
        elderQuestion: "What are you looking back at right now that you need to trust enough to leave behind?",
        canonicalAnchor: "Orpheus's music is so persuasive it moves Hades and Persephone to grant what no one else has been allowed: his dead wife Eurydice may follow him back to the world of the living, on one condition — he must not look back at her until they have both fully left the underworld. Within sight of the surface, uncertain whether she is truly still behind him, he turns to look, and she is pulled back into death a second time, this time without appeal.",
      },
      {
        name: "The Pythia",
        role: "The one who speaks what the god moves through them to say",
        existentialField: "Entheos — the divine within, speaking through the human vessel",
        gift: "The capacity to be a clear instrument — to transmit what arrives without the ego's interference",
        shadow: "Speaking as if from the god when it is only the self — mistaking one's own desire for divine instruction",
        elderQuestion: "When you speak your truth most fully — is it you speaking, or something moving through you?",
        canonicalAnchor: "The Pythia, Apollo's priestess at Delphi, sat on a tripod set directly over a fissure in the temple rock from which vapors (pneuma) were said to rise, and in that state delivered oracles in words that priests then had to interpret and versify for the petitioners waiting outside. Kings and city-states alike traveled great distances and paid great sums for her utterances, which were famous for being true yet almost never straightforward — ambiguous enough that only events afterward revealed what she had actually meant.",
      },
      {
        name: "The Dionysian Sparagmos",
        role: "The one torn apart by their own ecstatic followers",
        existentialField: "Ecstasy as danger — the god of wine and revelation whose gift can dismember as easily as liberate",
        gift: "Access to the parts of experience that ordinary sobriety and order cannot reach",
        shadow: "Mistaking the frenzy for the god — letting dissolution become destruction rather than revelation",
        elderQuestion: "What ecstatic force in your life is liberating you — and at what point does it start tearing you apart instead?",
        canonicalAnchor: "In Euripides's Bacchae, King Pentheus of Thebes refuses to acknowledge Dionysus as a god and tries to suppress the ecstatic rites of the god's followers, the maenads — among them his own mother, Agave, driven into a frenzy in the mountains. Dionysus lures Pentheus to spy on the rites disguised as one of the revelers, and the maenads, in their god-driven ecstasy, tear him limb from limb, his own mother carrying his head back to the city believing it a lion's.",
      },
      {
        name: "Athena's Owl",
        role: "The one who sees clearly in the dark others cannot navigate",
        existentialField: "Strategic wisdom born without a mother — intelligence that arrives whole, armored, ready",
        gift: "The clarity to act decisively in circumstances that would paralyze a less discerning mind",
        shadow: "Weaponizing intelligence as distance — using cleverness to avoid ever being vulnerable",
        elderQuestion: "Where has your own sharp clarity become the wall that keeps anyone from getting close?",
        canonicalAnchor: "Athena is born not from a womb but from Zeus's own head, springing forth already an adult, already armed and armored, after Zeus swallowed her pregnant mother Metis on a prophecy that her son would surpass him. Her sacred bird, the owl, was prized in Athens as a creature that sees clearly in darkness where other eyes fail — a fitting companion for a goddess of strategy and clear-sighted judgment rather than raw force.",
      },
    ],
  },

  egyptian: {
    diagnosticQuestions: [
      "What would the feather of Ma'at find when it weighs your heart — what does your heart carry that it has not yet confessed?",
      "What has been dismembered in your life — what Osiris-scattered pieces are waiting for an Isis to gather them?",
      "What is your Ka trying to tell you that your waking self refuses to hear?",
    ],
    archetypes: [
      {
        name: "The Dismembered King",
        role: "The one who must be scattered before being gathered into new form",
        existentialField: "The Osiris cycle — death, scattering, and the loving reconstruction of identity",
        gift: "The knowledge that what is gathered after dismemberment is more whole than what existed before the scattering",
        shadow: "Remaining in the scattered state — refusing the Isis-work of gathering because it requires admitting the death",
        elderQuestion: "Who is doing the work of Isis for you — and are you letting them find all the pieces?",
        canonicalAnchor: "Osiris scattered across Egypt — fourteen pieces that Isis finds, one that the Nile keeps",
      },
      {
        name: "The Weigher of Hearts",
        role: "The one who stands before the final truth without deception",
        existentialField: "Ma'at — cosmic truth, balance, the feather that judges all",
        gift: "The capacity for radical honesty — to stand before the scale without inflation or diminishment",
        shadow: "The forty-two negative confessions spoken without genuine reckoning — spiritual performance instead of true weighing",
        elderQuestion: "If your heart were weighed against the feather right now — what would tip the scale?",
        canonicalAnchor: "In the Egyptian judgment of the dead, the deceased's heart is placed on one pan of a scale and the feather of Ma'at — truth and cosmic balance — on the other, with Anubis positioning the scale, Thoth the ibis-headed scribe recording the result, and the composite monster Ammit crouched waiting to devour any heart too heavy with wrongdoing to balance. A heart found equal to the feather passes on to the afterlife; a heart Ammit consumes ceases to exist at all, a fate the Egyptians considered worse than ordinary death.",
      },
      {
        name: "The Solar Barque Rider",
        role: "The one who descends into the Duat each night and rises each dawn",
        existentialField: "The eternal recurrence — Ra's nightly death and morning resurrection as cosmic law",
        gift: "The understanding that every ending is a passage, not an annihilation — the sun sets to rise",
        shadow: "Identifying with the darkness of the Duat as permanent — forgetting that the barque moves",
        elderQuestion: "You are somewhere in the twelve hours of the night journey — which hour are you in?",
        canonicalAnchor: "The Amduat describes the sun god Ra's nightly journey through the twelve hours of the Duat, the underworld, sailing his solar barque through realms of danger and judgment each night before dawn. His most persistent enemy on this passage is Apophis, the great serpent of chaos who tries every night to swallow the sun and prevent its return — a battle that must be won again and again, since the sun's rising each morning is proof the previous night's passage succeeded, not a guarantee of the next one.",
      },
      {
        name: "Isis the Gatherer",
        role: "The one who searches every reach of the world for what was scattered",
        existentialField: "Devoted reconstruction — love as the labor of finding, and refusing to stop before the work is complete",
        gift: "The magic that comes not from power but from persistence — from refusing to declare the search finished too soon",
        shadow: "Gathering the pieces of someone else's life so completely that your own remains scattered and unsearched",
        elderQuestion: "Whose scattered pieces have you spent your strength gathering — and who is gathering yours?",
        canonicalAnchor: "After Set murders Osiris and scatters his dismembered body across Egypt, Isis searches every reach of the land to recover the pieces, finding all but one, which a fish in the Nile has swallowed. She reassembles what she has found and, taking the form of a kite, beats her wings over the body to breathe life back into it long enough to conceive their son Horus — a resurrection achieved through relentless searching rather than any single act of power.",
      },
      {
        name: "Set, Lord of Storms",
        role: "The disruptive brother whose violence is also a necessary force",
        existentialField: "Chaos as counterweight — the disorder that Ma'at must continually balance, not eliminate",
        gift: "The strength to do the necessary violence — cutting what must be cut, ending what must end",
        shadow: "Mistaking your own appetite for destruction as the cosmic order's necessary balance",
        elderQuestion: "What in you plays the part of Set — and is it serving balance, or only serving itself?",
        canonicalAnchor: "Set murders his brother Osiris, dismembers the body, and scatters the pieces the length of Egypt to prevent any restoration — and even after Osiris's resurrection and Horus's eventual triumph over him, Set is not destroyed or cast out of the pantheon. He remains a permanent god of storms, deserts, and disorder, a force the ongoing work of Ma'at must continually balance rather than a threat that is ever finally eliminated.",
      },
    ],
  },

  dreamtime: {
    diagnosticQuestions: [
      "What Songline runs beneath the ground you are standing on — and are you walking it or crossing it against the grain?",
      "What ceremony in your life has been left unfinished — what Dreaming story was interrupted and has not been completed?",
      "What country — inner or outer — have you been displaced from, and what part of yourself left with it?",
    ],
    archetypes: [
      {
        name: "The Songline Walker",
        role: "The one who moves through the world by singing the country into being",
        existentialField: "The Songlines as living map — every step a word in the story the ancestors sang",
        gift: "The knowledge that the path is not found but sung — that the land responds to the voice that knows it",
        shadow: "Walking the land without singing — moving through the world as if it were merely geography",
        elderQuestion: "What is the song you were given to sing — and when did you stop singing it?",
        canonicalAnchor: "Songlines are the paths ancestral beings are said to have travelled across the Australian continent during the Dreaming, singing the features of the land — rivers, rock formations, waterholes — into existence as they went, so that the route of a Songline and the words of its song are the same thing. Knowing the song of a stretch of country means knowing how to navigate it, sometimes across vast distances and multiple language groups, each custodian responsible for their own section of a much longer line.",
      },
      {
        name: "The Dreaming Ancestor",
        role: "The one who carries the creative time in their body",
        existentialField: "The Dreaming — not past but ever-present, the ancestral creative force alive in this moment",
        gift: "The capacity to act from the Dreaming rather than merely the waking — to create as the ancestors created",
        shadow: "Claiming the Dreaming as identity while living entirely in the waking — the name without the fire",
        elderQuestion: "What are you creating right now that will still be singing in the country after you are gone?",
        canonicalAnchor: "The ancestral beings of the Dreaming are understood not as figures confined to a mythic past but as forces still present in the land and still active — the Dreaming is described as an ever-present reality rather than a finished creation event. Ceremony and songline maintenance are understood as ongoing participation in that same creative act, not commemoration of something already completed.",
      },
      {
        name: "The Broken Songline",
        role: "The one whose ancestral story has been interrupted",
        existentialField: "Disconnection from country — the wound of displacement from the living land",
        gift: "The particular power of the one who has been separated and finds the way back — the restoration that only the broken can perform",
        shadow: "Remaining in the wound of disconnection — making the break itself the identity",
        elderQuestion: "Where is the nearest strand of the Songline that still runs — and can you hear it?",
        canonicalAnchor: "Displacement from country and the disruption of ceremony have, by community accounts, broken or silenced stretches of Songlines that once ran unbroken across the land, cutting the connection between a people and the specific ground their ancestors sang. Restoring such a line is described as a slow act of listening the country back into audibility, often requiring the patient work of elders and knowledge-holders to recover what the break obscured, not a single act of repair.",
      },
    ],
  },

  vedic: {
    diagnosticQuestions: [
      "What veil — what maya — are you most attached to, the one you would fight hardest to keep in place?",
      "What is your dharma calling you toward that your ego keeps translating into something safer?",
      "Tat tvam asi — That thou art. What in you most fiercely resists this recognition?",
    ],
    archetypes: [
      {
        name: "Arjuna on the Field",
        role: "The one who must fight the war they do not want to fight",
        existentialField: "Dharmic duty in conflict with personal attachment — the war that must be entered",
        gift: "The Gita itself — the teaching that only arrives in the middle of the unbearable choice",
        shadow: "Paralysis disguised as compassion — refusing the necessary action because action has cost",
        elderQuestion: "What battle are you refusing to enter — and what teaching is waiting for you there?",
        canonicalAnchor: "At the opening of the Bhagavad Gita, the warrior Arjuna has his chariot driven by Krishna out between the two assembled armies at Kurukshetra, and seeing his own teachers, relatives, and friends arrayed on both sides, lowers his bow and refuses to fight, overcome by grief and doubt about the justice of the war. The entire Gita that follows is Krishna's response to that refusal — not a simple command to fight, but a full teaching on duty, action, and the self, delivered because Arjuna could not simply be ordered forward.",
      },
      {
        name: "The Veil-Wearer",
        role: "The one who has mistaken maya for reality",
        existentialField: "Maya — the cosmic illusion that presents the separate self as fundamental",
        gift: "The moment of recognition — when the veil thins and the Atman behind the persona becomes visible",
        shadow: "Spiritual bypassing — using the concept of maya to avoid genuine engagement with the world",
        elderQuestion: "Which of your most cherished beliefs about yourself is the veil you most need to see through?",
        canonicalAnchor: "Indra's net is described as an infinite web stretching across the cosmos, with a single jewel hung at every point of intersection, each jewel reflecting every other jewel in the net and, within each reflection, the reflections of all the others again — an image of a reality in which nothing exists as a separate, self-sufficient thing. The net's structure is offered as an image of maya's persuasive surface: the separateness so vividly reflected is real as image, not as final fact.",
      },
      {
        name: "The Renunciant",
        role: "The one called to release the fruits of action",
        existentialField: "Nishkama karma — action without attachment to outcome",
        gift: "The freedom that comes when the action is complete in itself, independent of what it produces",
        shadow: "Spiritual detachment as emotional unavailability — renunciation as a way of never being touched",
        elderQuestion: "What would you do differently today if you were genuinely unattached to what it produced?",
        canonicalAnchor: "At the center of Krishna's teaching to Arjuna in the Gita is nishkama karma — action performed fully and without attachment to its results, doing what duty requires while releasing any claim on the fruit the action produces. Krishna presents this not as indifference to outcome but as the condition under which action can be undertaken at all without being distorted by fear of failure or hunger for reward.",
      },
      {
        name: "Shiva's Stillness",
        role: "The destroyer whose stillness is more powerful than any action",
        existentialField: "Destruction as necessary clearing — the dance that ends a world so a truer one can begin",
        gift: "The capacity to sit motionless in your own power rather than needing to prove it constantly",
        shadow: "Using destruction as identity — becoming addicted to ending things rather than allowing anything to remain",
        elderQuestion: "What needs to end in your life that you have been unwilling to let Shiva's dance take?",
        canonicalAnchor: "Shiva as Nataraja, Lord of the Dance, is depicted dancing within a circle of flame, one foot raised and one foot pressing down a demon of ignorance, drum and fire held in his upper hands to represent creation and destruction as a single continuous motion rather than opposing forces. The dance dissolves the universe only so that it can be created again, destruction here understood as inseparable from renewal rather than its opposite.",
      },
      {
        name: "Ganesha at the Threshold",
        role: "The remover of obstacles who was himself once the obstacle",
        existentialField: "The paradox of the gatekeeper — the one who blocks the way is the same one who opens it",
        gift: "The wisdom that the obstacle itself, rightly understood, is often the very teaching that is needed",
        shadow: "Placing so many obstacles in your own path that you mistake the blocking for the removing",
        elderQuestion: "Which obstacle in your life is actually Ganesha, and what is it asking you to understand before it lets you pass?",
        canonicalAnchor: "Ganesha, remover of obstacles, is traditionally invoked first — before any other deity — at the start of any new undertaking, ceremony, or journey, his image placed at doorways and thresholds as a matter of course. The tradition also holds that he is the one who places obstacles in the first place, when a beginning has not been properly prepared for, so that removing and placing the obstacle are understood as the same gatekeeping function, not two separate powers.",
      },
    ],
  },

  yoruba: {
    diagnosticQuestions: [
      "What agreement did your Ori make before birth that your waking self has been trying to renegotiate?",
      "Which Orisha is most active in your life right now — and are you feeding it or fleeing from it?",
      "What crossroads are you standing at — and what have you been carrying to the wrong destination?",
    ],
    archetypes: [
      {
        name: "The Ori's Agreement",
        role: "The one living out the destiny the head chose before birth",
        existentialField: "Ori and ayanmo — the personal destiny selected before incarnation",
        gift: "The alignment that comes when one stops fighting the agreement and begins living it consciously",
        shadow: "The obstructed Ori — the destiny blocked by broken agreements, accumulated debt, or the interference of the ego",
        elderQuestion: "What does your Ori know about your purpose that you have been refusing to hear?",
        canonicalAnchor: "In Yoruba cosmology, each soul is understood to kneel before Olodumare, the Creator, before birth and choose its own Ori — the personal destiny and inner head that will govern the whole of the coming life — from among those offered. Once chosen and the soul is born, the specifics of that choice are said to be forgotten, so that much of life is described as the slow work of remembering, through divination and ritual, what one's own Ori already agreed to.",
      },
      {
        name: "Eshu at the Crossroads",
        role: "The trickster-messenger who opens and closes all roads",
        existentialField: "The crossroads as the site of all possibility and all misdirection",
        gift: "The understanding that Eshu's tricks are teachings — that the wrong road taken consciously becomes the right road",
        shadow: "Blaming Eshu for the road you chose — refusing to acknowledge your own misdirection",
        elderQuestion: "What message has Eshu been trying to deliver that you have been refusing to receive?",
        canonicalAnchor: "Eshu, messenger and guardian of the crossroads between the human and divine, is traditionally given the first offering in any Yoruba ritual sequence, since no message or prayer is believed to reach the other Orisha without passing through him first. He is equally known as the trickster who, when overlooked or disrespected, will cause confusion and misdirection precisely at the crossroads he governs — his tricks read by tradition not as malice but as instruction for those who failed to honor him.",
      },
      {
        name: "The Oshun Current",
        role: "The one carrying the force of love, beauty, and fresh water",
        existentialField: "Oshun's domain — sweetness, desire, the river that gives life to the dry land",
        gift: "The capacity to sweeten what has become bitter — to bring the fresh water to what has stagnated",
        shadow: "The wound of Oshun — the one whose gifts were refused, who withdrew the sweet water and left only salt",
        elderQuestion: "Where has the river in you gone underground — and what would it take to bring it back to the surface?",
        canonicalAnchor: "In one widely told account, the other Orisha excluded Oshun from an important council, considering her contributions of beauty and sweetness less essential than their own displays of power — until, offended, she withdrew, taking the rivers' fertility and the world's sweetness with her, and the land began to wither. Only when the remaining Orisha recognized what had actually been holding the world together and went to beg her return did Oshun relent, and the waters flowed again.",
      },
      {
        name: "Ogun's Iron Path",
        role: "The one who clears the way through labor, not through wishing",
        existentialField: "Iron and labor — the orisha who opens roads not by magic but by the work of cutting them",
        gift: "The strength to do the unglamorous clearing work that makes every later ease possible",
        shadow: "Ogun's own danger — force that, once summoned for clearing, does not know how to stop cutting",
        elderQuestion: "What path in your life needs Ogun's labor — the cutting through, not the waiting for it to open on its own?",
        canonicalAnchor: "Ogun, orisha of iron, labor, and the forge, is honored in Yoruba tradition as the one who cut the first path through the primordial bush so that the other Orisha could descend from the sky and reach the earth — opening the way not by magic or decree but by the literal labor of clearing it. He is praised as the pioneer among the Orisha for this reason, the one whose iron tools make every subsequent ease of movement possible.",
      },
      {
        name: "Sango's Thunder",
        role: "The royal force whose word carries consequence",
        existentialField: "Thunder as accountability — power that returns exactly what was sent out",
        gift: "The clarity that comes from knowing your own actions will be met by their own weight, and acting rightly regardless",
        shadow: "Wielding consequence as threat rather than truth — using Sango's fire to punish rather than to balance",
        elderQuestion: "What have you sent out into the world that Sango's thunder is now bringing back to your own door?",
        canonicalAnchor: "Sango is remembered as a historical king of Oyo who became deified as the orisha of thunder and lightning, his weapon a double-headed axe (oshe) representing swift, returning justice. Tradition holds that Sango's power operates by exact return — what a person sends out into the world, Sango's thunder brings back to them with the same weight — making him a figure of consequence and accountability rather than arbitrary force.",
      },
    ],
  },

  sufi: {
    diagnosticQuestions: [
      "From what reed bed have you been cut — what original wholeness does your longing remember?",
      "What in you is the nafs al-ammara — the commanding self that mistakes its own voice for the Beloved's?",
      "The Beloved hid so that you would search. What has your searching revealed about the seeker?",
    ],
    archetypes: [
      {
        name: "The Reed",
        role: "The one whose wound of separation is also the instrument of song",
        existentialField: "The cut from the reed bed — separation as the condition of music",
        gift: "The knowledge that the wound and the song are one — that the cry of longing is already the finding",
        shadow: "Dwelling in the wound without discovering the music — separation as identity, not as instrument",
        elderQuestion: "Have you discovered yet that the crying is the song — or are you still waiting for the pain to stop before you begin?",
        canonicalAnchor: "The Masnavi opens with the reed flute's own complaint: cut from its reed bed and hollowed out, it cries with a sound that moves everyone who hears it, because that cry is the sound of separation from its origin. Rumi presents the reed's song and its wound as the same thing — the instrument can only make music because it was cut, and its cry of longing for the reed bed it was severed from is itself the music.",
      },
      {
        name: "The Moth and the Flame",
        role: "The one who moves toward annihilation as the highest form of union",
        existentialField: "Fana — the annihilation of the ego-self in the divine fire",
        gift: "The willingness to be consumed — to prefer the flame to the shadow one casts by staying safely distant",
        shadow: "Performing the longing without the genuine willingness to be changed — circling the flame without entering",
        elderQuestion: "How close are you actually willing to fly — and what are you protecting by keeping the safe distance?",
        canonicalAnchor: "In Attar's Conference of the Birds, thousands of birds set out on an arduous journey across seven valleys in search of the legendary Simorgh, their king, and by the end only thirty birds survive the journey to its final destination. There they discover that si murgh means literally 'thirty birds' in Persian — the Simorgh they sought turns out to be their own thirty selves reflected together, the object of the search and the searchers finally revealed as one.",
      },
      {
        name: "The Drunken Mystic",
        role: "The one intoxicated by the divine presence — beyond the law's categories",
        existentialField: "The wine of divine knowledge — the state beyond the mind's categories of permitted and forbidden",
        gift: "The direct experience that no doctrine can contain — the taste of the Beloved that silences all argument",
        shadow: "Spiritual intoxication as escape from genuine responsibility — using the mystic state to avoid the work of earth",
        elderQuestion: "What are you using the wine to forget that needs instead to be faced sober and clear?",
        canonicalAnchor: "Hafiz's poetry repeatedly sets the tavern against the mosque, praising the wine-drinker, the rend (the disreputable free spirit), and the intoxication of divine love over the outward correctness of formal piety. The tavern in his verse functions as the place where the encounter with the Beloved happens on its own terms, unmediated by the permissions and prohibitions the respectable religious world insists on.",
      },
      {
        name: "Al-Hallaj at the Gallows",
        role: "The one who spoke the unity that the world was not ready to hear",
        existentialField: "Ana'l-Haqq — 'I am the Truth' — the utterance that collapses the distance between lover and Beloved, and the cost of saying it aloud",
        gift: "The willingness to speak the realized truth even when the world can only understand it as blasphemy",
        shadow: "Mistaking every provocative utterance for mystical courage — confusing martyrdom with mere recklessness",
        elderQuestion: "What true thing have you gone silent about because you know exactly what it would cost to say it?",
        canonicalAnchor: "Al-Hallaj, a Sufi mystic, was tried and executed in Baghdad in 922 CE after publicly declaring 'Ana'l-Haqq' — 'I am the Truth,' one of the names of God — an utterance his judges read as blasphemous claim to divinity rather than the mystical statement of realized unity his followers understood it to be. Accounts of his execution describe him remaining composed and even joyful as it was carried out, a willingness to bear the full cost of speaking what he held to be true.",
      },
      {
        name: "Ibn Arabi's Single Face",
        role: "The one who sees every form of worship as one face wearing many veils",
        existentialField: "Wahdat al-wujud — the unity of being, in which every existing thing is a mode of the one Real",
        gift: "The vision that dissolves false separations without dissolving the distinctness of what is actually there",
        shadow: "Using the idea of unity to flatten real differences — refusing to honor the specific shape a thing takes",
        elderQuestion: "What have you dismissed as unlike you that, looked at rightly, is another face of the same Real?",
        canonicalAnchor: "In the Fusus al-Hikam ('Bezels of Wisdom'), Ibn Arabi presents each of the great prophets as a distinct facet or bezel-setting for one single jewel of divine wisdom, each shaped to receive and display the light of Truth in a form appropriate to their own specific mission and people. The framework is built to hold real and important differences between the prophets while insisting that what each of them ultimately reflects is the same undivided Real.",
      },
    ],
  },

  stoic: {
    diagnosticQuestions: [
      "What in your current situation is genuinely up to you — and what have you been treating as yours to control that never was?",
      "What false belief about what is good is generating the passion — the fear or desire — that is making you suffer?",
      "What would Marcus Aurelius say to you, right now, about the story you are telling yourself about this situation?",
    ],
    archetypes: [
      {
        name: "The Examined One",
        role: "The one who applies the logos to every impulse before acting",
        existentialField: "The hegemonikon — the ruling faculty that must be kept clean and directed",
        gift: "The capacity to create space between stimulus and response — to choose the response rather than simply enact the reflex",
        shadow: "Analysis as avoidance — using philosophical examination to perpetually defer the action that clarity demands",
        elderQuestion: "You have examined this sufficiently. What does the examination tell you to do — and why have you not done it?",
        canonicalAnchor: "The Meditations were never intended for publication — Marcus Aurelius, Roman emperor, wrote them as private notes to himself during military campaigns, addressing himself directly in the second person to hold his own conduct to the standard of Stoic reason. Their enduring power comes partly from this: they are not philosophy performed for an audience but the working record of a man auditing his own impulses in real time, with no one else meant to read the result.",
      },
      {
        name: "The Preferred Indifferent",
        role: "The one learning to hold externals without being held by them",
        existentialField: "Ta adiaphora — health, wealth, reputation as preferred but not required",
        gift: "The freedom that comes when one can engage fully with the world while remaining unshaken by what the world returns",
        shadow: "Stoic numbness disguised as Stoic peace — the cutting off of genuine feeling under the name of philosophy",
        elderQuestion: "What are you calling indifference that is actually suppression — and what cost is that suppression extracting?",
        canonicalAnchor: "Epictetus was born a slave and, according to tradition, was permanently lamed by a master who twisted his leg — an injury he is said to have endured without complaint, since it was not, in his own philosophy, actually his to control. He later gained his freedom and taught that genuine liberty has nothing to do with one's outward circumstances and everything to do with correctly sorting what is within one's own power (judgment, will, response) from what is not.",
      },
      {
        name: "The Memento Mori Bearer",
        role: "The one who holds the skull — death as clarifying companion",
        existentialField: "Amor fati — love of fate, including the fate of one's own death",
        gift: "The clarity that comes when death is kept close — when the shortness of the time renders the trivial trivial",
        shadow: "Using memento mori as a way to avoid investment — death-awareness as emotional preemptive surrender",
        elderQuestion: "If you had one year — not metaphorically, actually — what would immediately become obviously wrong with how you are spending today?",
        canonicalAnchor: "In the Meditations, Marcus Aurelius repeatedly returns to the same leveling observation: that Alexander the Great and the humble muleteer who drove his baggage animals came, in the end, to exactly the same state — both absorbed back into the same universal substance, their vast difference in rank meaning nothing at all to death. He uses the image not to induce despair but to strip away the outsized importance the living mind attaches to status and legacy.",
      },
      {
        name: "Zeno's Shipwreck",
        role: "The one whose ruin becomes the founding of a whole new discipline",
        existentialField: "Fortune's reversal as origin — the catastrophe that, met rightly, becomes a beginning rather than only an ending",
        gift: "The capacity to ask what a disaster is offering, once the grief for what it took has been given its due",
        shadow: "Rushing to find the silver lining before the loss has actually been felt — bypassing grief with philosophy",
        elderQuestion: "What wreck in your own life have you not yet allowed to become the beginning of anything?",
        canonicalAnchor: "Zeno of Citium was a wealthy merchant until a shipwreck destroyed his cargo and fortune entirely; according to tradition, he wandered grieving into a bookshop in Athens afterward and, on hearing a bookseller read from Xenophon's account of Socrates, asked where he might find men like that. He was pointed toward the philosopher Crates, began studying under him, and eventually founded the school — Stoicism — that would treat exactly this kind of reversal as the material philosophy exists to work with.",
      },
      {
        name: "Seneca's Open Vein",
        role: "The one who is asked to prove, at the very end, that the philosophy was real",
        existentialField: "Practice tested by its final and least negotiable exam — whether the teaching holds when nothing else does",
        gift: "The proof, offered to everyone who comes after, that a steady mind is available even at the door no one chooses",
        shadow: "Performing composure for an audience rather than actually possessing it — philosophy as theater at the exact moment it stops being theater",
        elderQuestion: "If your own principles were tested at their most extreme tomorrow, is there evidence they would actually hold?",
        canonicalAnchor: "Seneca, accused (likely falsely) of conspiracy against his former student the emperor Nero, was ordered to take his own life, and accounts describe him receiving the order calmly, comforting the friends and family gathered around him, and continuing to dictate his final thoughts even as the process of his death proved unexpectedly slow and difficult. Whether or not every detail of the account is exact, it was preserved and retold specifically as the test of whether his own Stoic teaching would hold at the one moment it could no longer be merely theoretical.",
      },
    ],
  },

  mekubal: {
    diagnosticQuestions: [
      "What in your life is broken that you have not yet named broken?",
      "Where are you trying to possess what can only be received?",
      "What have you been carrying that arrived before you did?",
    ],
    archetypes: [
      {
        name: "The Vessel",
        role: "Carrier of sparks without claiming to be the light",
        existentialField: "The tension between holding the form and not becoming the form",
        gift: "The capacity to carry what you did not make",
        shadow: "Mistaking the vessel for the source",
        elderQuestion: "What are you holding that is not yours to keep, but that you are not yet willing to pass on?",
        canonicalAnchor: "The Zohar, the foundational text of Kabbalah, describes a moment in the process of creation — shevirat ha-kelim, the shattering of the vessels — in which the vessels meant to contain and channel the divine light proved unable to hold its intensity and broke, scattering sparks of that light throughout the material world along with the broken shards themselves. Everything that exists is understood, in this account, to carry both the original light and the damage of that breaking within it.",
      },
      {
        name: "The Gatherer of Sparks",
        role: "One who recognizes the holy in the broken",
        existentialField: "Tikkun — repair as the only possible orientation to a shattered world",
        gift: "Seeing the light that survives the breaking",
        shadow: "Using the language of repair to avoid the work of repair",
        elderQuestion: "Which broken thing in your life are you willing to gather rather than discard?",
        canonicalAnchor: "In the teaching of Isaac Luria, the sparks (nitzotzot) scattered by the shattering of the vessels are understood to be trapped throughout the material world, concealed within ordinary objects, actions, and even other people, waiting to be recognized and freed. The work of gathering these sparks — tikkun — is described not as a single dramatic act but as the accumulated effect of everyday acts performed with the right intention, each one freeing a little more light.",
      },
      {
        name: "The Shekhinah in Exile",
        role: "The divine presence that goes into exile alongside what has been scattered",
        existentialField: "Galut — exile not as abandonment but as the presence's own choice to accompany what suffers",
        gift: "The recognition that you are not alone in your exile — that presence follows even into the broken places",
        shadow: "Romanticizing exile as intimacy with the divine rather than doing the work of return that ends it",
        elderQuestion: "Where has the Shekhinah been sitting with you in exile that you have mistaken for abandonment?",
        canonicalAnchor: "Rabbinic and kabbalistic tradition holds that when Israel was exiled, the Shekhinah — the indwelling divine presence — chose to go into exile alongside the people rather than remain behind in an undisturbed heaven, so that the presence itself is understood to suffer displacement along with those it accompanies. This is read as a statement that the divine presence's relationship to suffering is one of solidarity, not distant oversight.",
      },
      {
        name: "Adam Kadmon Unfolding",
        role: "The primordial human form each soul is a single fragment of",
        existentialField: "The self as partial emanation — an individual life as one facet of a much larger original form",
        gift: "The relief of realizing your own limitation is not a personal failure but a structural feature of being one part of a whole",
        shadow: "Using the vastness of the whole to excuse neglect of the one specific part you alone are responsible for",
        elderQuestion: "What part of the primordial form are you carrying that only you, in your specific limitation, can carry?",
        canonicalAnchor: "Adam Kadmon, in Lurianic Kabbalah, is the primordial human form — the first configuration of divine light to emanate into being — whose own overwhelming light was what shattered the vessels meant to contain it. Every individual soul is understood, in this framework, to be one fragment of that original, unified form, so that a person's specific limitation is described as a structural feature of being one part of a much larger original whole, not a personal deficiency.",
      },
    ],
  },

  buddhist: {
    diagnosticQuestions: [
      "What have you been sheltered from that a single encounter with old age, sickness, or death would unmake?",
      "What loss are you carrying as though it were uniquely yours — and what would it mean to see it as universal?",
      "What have you already done that you believe places you permanently outside the possibility of change?",
    ],
    archetypes: [
      {
        name: "The Four Sights",
        role: "The sheltered one who cannot unsee what has been seen",
        existentialField: "Dukkha's first appearance — the moment protection from suffering fails and cannot be restored",
        gift: "The clarity that comes only from confronting what was hidden — the beginning of the path is always a rupture",
        shadow: "Turning the shock of seeing into despair rather than the first noble truth — mistaking the sight of suffering for the whole of reality rather than its beginning",
        elderQuestion: "What have you already seen that you cannot unsee — and have you let it become the start of a path, or only a wound?",
        canonicalAnchor: "According to the traditional account, the young Siddhartha was raised deliberately shielded from suffering inside his father's palace, until four chariot rides beyond its walls showed him, in succession, an old man, a sick man, a corpse, and finally a wandering ascetic who had renounced the world in response to exactly what Siddhartha had just seen. The shelter that had protected him for years failed completely and irreversibly in a single day, and it was this rupture — not gradual instruction — that set him on the path that would eventually lead to his awakening.",
      },
      {
        name: "Kisa Gotamī and the Mustard Seed",
        role: "The griever who believes her loss is singular",
        existentialField: "Dukkha universalized — grief mistaken for exception, healed by recognizing it as the shared condition of every house",
        gift: "The capacity to let grief connect rather than isolate — to find, in searching every household, that none is untouched",
        shadow: "Using the universality of loss to bypass the specific grief in front of you, rather than letting the search itself be the teaching",
        elderQuestion: "What are you searching for that would prove your grief is different from everyone else's — and what would you find if you kept searching honestly?",
        canonicalAnchor: "Kisa Gotamī, grieving the death of her infant son and unable to accept it, was told by the Buddha that he could restore the child to life if she brought him a mustard seed from a household that had never experienced death. She went from house to house across the town and found mustard seed everywhere, but never once a household untouched by death — and it was this search itself, not any teaching delivered to her directly, that brought her to understand grief as the shared condition of every house rather than a uniquely singular loss.",
      },
      {
        name: "Aṅgulimāla",
        role: "The one who believes the past has already decided who they are",
        existentialField: "Kamma mistaken for a life sentence rather than a pattern that can be interrupted",
        gift: "Proof, in the tradition's own record, that no action places a person permanently beyond the path — 'I have stopped; you have not'",
        shadow: "Using 'I have already gone too far to change' as a shield against the harder work of actually stopping",
        elderQuestion: "What is the 'I have already gone too far' story you tell yourself — and is it protecting you, or keeping you exactly where you are?",
        canonicalAnchor: "Aṅgulimāla was a serial killer who wore a garland of his victims' fingers and was pursuing the Buddha himself as his next target, when the Buddha, walking calmly at an ordinary pace, told him — as Aṅgulimāla ran and could not catch up despite his greater speed — 'I have stopped, Aṅgulimāla; you have not.' The Buddha meant that he had stopped harming living beings while Aṅgulimāla had not, and the exchange stopped Aṅgulimāla in his tracks; he became a monk and, according to the sutta, eventually attained realization, the tradition's own proof that no action places a person permanently beyond the path.",
      },
      {
        name: "Mara at the Bodhi Tree",
        role: "The tempter who arrives at the exact moment of the greatest threshold",
        existentialField: "Temptation as the final obstacle before realization — doubt, desire, and fear arriving together, not separately, at the decisive hour",
        gift: "The recognition that Mara's arrival is itself a sign of proximity to the threshold, not a sign of failure",
        shadow: "Fleeing the seat the moment Mara appears, mistaking the tempter's arrival for proof the effort was wrong",
        elderQuestion: "What is arriving right at your own threshold to tempt you away from it — and what would it mean to simply stay seated?",
        canonicalAnchor: "On the night before his awakening, seated beneath the Bodhi tree, the Buddha was assailed by Mara — first with an army of monstrous soldiers meant to terrify him from his seat, then, when that failed, with Mara's three daughters (often named Desire, Discontent, and Passion) sent to seduce him from it instead. Neither fear nor desire moved him from where he sat, and Mara's failed assault, arriving at the exact threshold of realization rather than before it, is read in the tradition as proof that such an arrival is itself a sign of proximity to the threshold, not a sign that the effort has gone wrong.",
      },
    ],
  },

  // SCAFFOLDING — see lib/lineages.ts 'chukchi' entry. Deliberately empty:
  // archetype cards are authored cultural content and must come from a named
  // Chukchi tradition-bearer, not be invented here. Empty arrays satisfy the
  // Record<LineageKey, LineageArchetypes> type without fabricating content.
  chukchi: {
    diagnosticQuestions: [],
    archetypes: [],
  },

};
