#!/usr/bin/env python3
"""
scripts/export_checklist.py

ARCH-01: Sheet Generator.
Reads governance/checklist.yaml (the source of truth) and writes a
publishable .xlsx matching the original Master Checklist format,
including live COUNTIF-based STATUS SUMMARY / PHASE SUMMARY sections
(formulas, not hardcoded counts -- they recalculate if the yaml grows).

Usage:
    python3 scripts/export_checklist.py [output_path]

Default output: governance/checklist-generated.xlsx
Run scripts/recalc.py (from the xlsx skill) on the output afterward to
populate formula values and check for Excel errors before publishing.
"""
import sys
import yaml
from pathlib import Path
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

REPO_ROOT = Path(__file__).resolve().parent.parent
CHECKLIST_YAML = REPO_ROOT / "governance" / "checklist.yaml"

COLUMNS = [
    ("id", "ID", 12),
    ("status", "Status", 14),
    ("phase", "Phase", 20),
    ("priority_band", "Priority Band", 12),
    ("score", "Score", 8),
    ("tier_group", "Tier / Group", 32),
    ("category", "Category", 20),
    ("item", "Item", 40),
    ("description", "Description", 50),
    ("mitigation", "Mitigation", 40),
    ("steps", "Steps (1.a / 1.b …)", 50),
    ("importance", "Importance (1-5)", 10),
    ("impact", "Impact (1-5)", 10),
    ("effort", "Effort (1-5)", 10),
    ("leverage", "Leverage", 10),
    ("owner", "Owner", 18),
    ("depends_on", "Depends On", 18),
    ("evidence", "Evidence / Verification", 30),
    ("status_update", "Status Update", 40),
    ("cadence", "Cadence", 24),
]

FONT_NAME = "Arial"
HEADER_FILL = PatternFill("solid", fgColor="D9D9D9")


def load_rows():
    if not CHECKLIST_YAML.exists():
        sys.exit(f"ERROR: {CHECKLIST_YAML} not found. ARCH-01 checklist.yaml must exist first.")
    with open(CHECKLIST_YAML) as f:
        data = yaml.safe_load(f)
    rows = data.get("rows", [])
    if not rows:
        sys.exit("ERROR: checklist.yaml has no rows under 'rows:' key.")
    return rows


def fmt_depends(dep):
    if not dep:
        return "—"
    return ", ".join(dep)


def build_workbook(rows):
    wb = Workbook()
    ws = wb.active
    ws.title = "Master Checklist"

    # Title rows
    ws.append(["AHAU AI / THE ELDER — Master Checklist (generated from governance/checklist.yaml)"])
    ws.append(["Generated by scripts/export_checklist.py — DO NOT hand-edit this file. Edit governance/checklist.yaml instead."])
    ws.append([])

    header_row_idx = 4
    ws.append([label for _, label, _ in COLUMNS])
    for col_idx, (_, _, width) in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=header_row_idx, column=col_idx)
        cell.font = Font(name=FONT_NAME, bold=True)
        cell.fill = HEADER_FILL
        ws.column_dimensions[get_column_letter(col_idx)].width = width

    # Group rows by section, preserving original section-header rows
    sections = {}
    for r in rows:
        sections.setdefault(r.get("section") or "UNSECTIONED", []).append(r)

    data_start_row = header_row_idx + 1
    cur_row = data_start_row
    first_data_row = None
    for section_name, section_rows in sections.items():
        ws.cell(row=cur_row, column=1, value=f"— {section_name} —").font = Font(name=FONT_NAME, bold=True, italic=True)
        cur_row += 1
        for r in section_rows:
            if first_data_row is None:
                first_data_row = cur_row
            values = []
            for key, _, _ in COLUMNS:
                if key == "depends_on":
                    values.append(fmt_depends(r.get("depends_on")))
                else:
                    values.append(r.get(key) if r.get(key) not in (None, "") else "—")
            for col_idx, val in enumerate(values, start=1):
                c = ws.cell(row=cur_row, column=col_idx, value=val)
                c.font = Font(name=FONT_NAME)
                c.alignment = Alignment(wrap_text=True, vertical="top")
            cur_row += 1
    last_data_row = cur_row - 1

    # Blank separator
    cur_row += 1

    # STATUS SUMMARY -- live COUNTIF formulas, not hardcoded
    status_col_letter = get_column_letter(2)  # column B = status
    ws.cell(row=cur_row, column=1, value="STATUS SUMMARY").font = Font(name=FONT_NAME, bold=True)
    cur_row += 1
    for status_label in ["DONE", "IN PROGRESS", "BLOCKED", "NOT STARTED"]:
        ws.cell(row=cur_row, column=1, value=status_label).font = Font(name=FONT_NAME)
        formula = f'=COUNTIF({status_col_letter}{first_data_row}:{status_col_letter}{last_data_row},"{status_label}")'
        ws.cell(row=cur_row, column=2, value=formula).font = Font(name=FONT_NAME)
        cur_row += 1
    ws.cell(row=cur_row, column=1, value="TOTAL TRACKED").font = Font(name=FONT_NAME, bold=True)
    ws.cell(row=cur_row, column=2, value=f"=SUM(B{cur_row-4}:B{cur_row-1})").font = Font(name=FONT_NAME, bold=True)

    wb.save(OUTPUT_PATH)


if __name__ == "__main__":
    OUTPUT_PATH = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO_ROOT / "governance" / "checklist-generated.xlsx"
    rows = load_rows()
    build_workbook(rows)
    print(f"Wrote {OUTPUT_PATH} from {len(rows)} rows in {CHECKLIST_YAML}")
    print("Next: run scripts/recalc.py on the output to populate formula values and check for errors,")
    print("e.g.:  python3 /mnt/skills/public/xlsx/scripts/recalc.py governance/checklist-generated.xlsx")
